before_script:
  - apt update
  - apt install -y build-essential cmake wget rpm libboost-program-options-dev

build:debian:9:
  stage: build
  image: debian:9
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - wget -O libuInputPlus.deb 'https://gitlab.com/ReimuNotMoe/libuInputPlus/-/jobs/artifacts/master/raw/build/libuInputPlus_0.1.3_.deb?job=package:debian:9'
    - wget -O libevdevPlus.deb 'https://gitlab.com/ReimuNotMoe/libevdevPlus/-/jobs/artifacts/master/raw/build/libevdevPlus_0.1.0_.deb?job=package:debian:9'
    - dpkg -i libuInputPlus.deb && dpkg -i libevdevPlus.deb
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:debian:9:
  stage: deploy
  dependencies:
    - build:debian:9
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/ydotool_static"


build:ubuntu:18.04:
  stage: build
  image: ubuntu:18.04
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - wget -O libuInputPlus.deb 'https://gitlab.com/ReimuNotMoe/libuInputPlus/-/jobs/artifacts/master/raw/build/libuInputPlus_0.1.3_.deb?job=package:ubuntu:18.04'
    - wget -O libevdevPlus.deb 'https://gitlab.com/ReimuNotMoe/libevdevPlus/-/jobs/artifacts/master/raw/build/libevdevPlus_0.1.0_.deb?job=package:ubuntu:18.04'
    - dpkg -i libuInputPlus.deb && dpkg -i libevdevPlus.deb
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:18.04:
  stage: deploy
  dependencies:
    - build:ubuntu:18.04
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/ydotool_static"


build:ubuntu:19.04:
  stage: build
  image: ubuntu:19.04
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build
    - wget -O libuInputPlus.deb 'https://gitlab.com/ReimuNotMoe/libuInputPlus/-/jobs/artifacts/master/raw/build/libuInputPlus_0.1.3_.deb?job=package:ubuntu:19.04'
    - wget -O libevdevPlus.deb 'https://gitlab.com/ReimuNotMoe/libevdevPlus/-/jobs/artifacts/master/raw/build/libevdevPlus_0.1.0_.deb?job=package:ubuntu:19.04'
    - dpkg -i libuInputPlus.deb && dpkg -i libevdevPlus.deb
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-O1 -g' ..
    - make

package:ubuntu:19.04:
  stage: deploy
  dependencies:
    - build:ubuntu:19.04
  script:
    - cd build && make package
  artifacts:
    paths:
      - "build/*.deb"
      - "build/ydotool_static"

